clear
clc 
close all

MGP_plots; 

%code to make heat maps of all 106 schools (authority and hubs). Got tossed
%from the paper, but might be needed in review. 

%list of school names from schools_list
school_names={"Arizona State University",...
    "Auburn University",...
    "Boston University",...
    "Brown University",...
    "California Institute of Technology",...
    "Carnegie Mellon University",...
    "Case Western Reserve University",...
    "City University of New York",...
    "Colorado State University",...
    "Columbia University",...
    "Cornell University",...
    "Dartmouth College",...
    "Duke University",...
    "Emory University",...
    "Florida State University",...
    "Georgia Institute of Technology",...
    "Harvard University",...
    "Illinois Institute of Technology",...
    "Indiana University",...
    "Iowa State University",...
    "Kansas State University",...
    "Louisiana State University",...
    "Massachusetts Institute of Technology",...
    "Michigan State University",...
    "Montana State University",...
    "New Jersey Institute of Technology",...
    "New York University",...
    "North Carolina State University",...
    "Northwestern University",...
    "Oklahoma State University",...
    "Oregon State University",...
    "Princeton University",...
    "Purdue University",...
    "Rensselaer Polytechnic Institute",...
    "Rice University",...
    "Rutgers University, New Brunswick",...
    "Southern Methodist University",...
    "Stanford University",...
    "State University of New York at Binghamton",...
    "State University of New York at Buffalo",...
    "State University of New York at Stony Brook",...
    "Syracuse University",...
    "Temple University",...
    "Texas A&M University",...
    "Texas Tech University",...
    "The George Washington University",...
    "The Johns Hopkins University",...
    "The Ohio State University",...
    "The Pennsylvania State University",...
    "The University of Chicago",...
    "The University of Iowa",...
    "The University of New Mexico",...
    "The University of North Carolina at Chapel Hill",...
    "The University of Oklahoma",...
    "Tulane University",...
    "University of Arizona",...
    "University of Arkansas",...
    "University of California, Berkeley",...
    "University of California, Davis",...
    "University of California, Irvine",...
    "University of California, Los Angeles",...
    "University of California, Riverside",...
    "University of California, San Diego",...
    "University of California, Santa Barbara",...
    "University of California, Santa Cruz",...
    "University of Cincinnati",...
    "University of Colorado at Boulder",...
    "University of Connecticut",...
    "University of Delaware",...
    "University of Florida",...
    "University of Georgia",...
    "University of Hawaii",...
    "University of Houston",...
    "University of Illinois at Chicago",...
    "University of Illinois at Urbana-Champaign",...
    "University of Kansas",...
    "University of Kentucky",...
    "University of Maryland Baltimore County",...
    "University of Maryland College Park",...
    "University of Massachusetts Amherst",...
    "University of Miami",...
    "University of Michigan",...
    "University of Minnesota - Twin Cities",...
    "University of Missouri - Columbia",...
    "University of Nebraska-Lincoln",...
    "University of Notre Dame",...
    "University of Oregon",...
    "University of Pennsylvania",...
    "University of Pittsburgh",...
    "University of Rochester",...
    "University of Southern California",...
    "University of Tennessee - Knoxville",...
    "University of Texas at Arlington",...
    "University of Texas at Austin",...
    "University of Texas at Dallas",...
    "University of Utah",...
    "University of Virginia",...
    "University of Washington",...
    "University of Wisconsin-Madison",...
    "University of Wisconsin-Milwaukee",...
    "Vanderbilt University",...
    "Virginia Polytechnic Institute and State University",...
    "Washington State University",...
    "Washington University in St. Louis",...
    "Wayne State University",...
    "Yale University"};

%rolling years (first year in decade) for Figs 9-10

rolling_years={'1950','1951','1952','1953','1954', ...
    '1955', '1956', '1957', '1958', '1959' ...
    '1960', '1961', '1962', '1963', '1964', ...
    '1965', '1966', '1967', '1968', '1969', ...
    '1970', '1971', '1972', '1973', '1974', ...
    '1975', '1976', '1977', '1978', '1979', ...
    '1980', '1981', '1982', '1983', '1984', ...
    '1985', '1986', '1987', '1988', '1989', ...
    '1990', '1991', '1992', '1993', '1994', ...
    '1995', '1996', '1997', '1998', '1999', ...
    '2000', '2001', '2002', '2003', '2004', ...
    '2005', '2006', '2007', '2008', '2009','2010'};

%authority heat map

figure(111)
clf
set(gcf,'Position',figpos)
colormap('jet')
imagesc(auth_in_order)
colorbar
ax = gca;
set(gca,'fontsize', 6)
title('Authority Scores by Department between 1950-2010','FontSize',fs1)
ax.YTick = [1:length(school_list)];
% Set TickLabels;
ax.YTickLabel = school_names;
ax.XTick = [1:61];
ax.XTickLabel = rolling_years;

%authority heat map

figure(112)
clf
set(gcf,'Position',figpos)
colormap('jet')
imagesc(hubs_in_order)
colorbar
ax = gca;
set(gca,'fontsize', 6)
title('Hubs Scores by Department between 1950-2010','FontSize',fs1)
ax.YTick = [1:length(school_list)];
%Set TickLabels;
ax.YTickLabel = school_names;
ax.XTick = [1:61];
ax.XTickLabel = rolling_years;